[package]
name = "little-engine"
version = "0.1.0"
authors = ["zovt <zovt@posteo.de>"]
description = "The Little Game Engine That Could"
license = "MPL-2.0"

[dependencies]
cgmath = "0.15.0"
glutin = "0.10.0"
chrono = "0.4"
